name: Build and Deploy to Selfhosted

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t jisho-app:latest .

    - name: Stop and remove old container
      run: |
        docker stop jisho-app || true
        docker rm jisho-app || true

    - name: Run container
      run: |
        docker run -d \
          --name jisho-app \
          -p 3344:5000 \
          jisho-app:latest